

```{r}
library("ModBart")
library("SoftBart") # MFM version
library("mvtnorm")
library("Rcpp")
```

```{r}
## Call the SepBART function
source('../00-functions-block.R')

## Load the data
data <- readRDS("../data/intermediate/SepBART_data/preprocessed_data/all_merged_2000.rds")

# Set the seed for reproducibility
set.seed(123)

# Generate 1000 random row indices
random_indices <- sample(nrow(data), size = 100, replace = FALSE)

# Subset the dataframe using the random indices
random_sample <- data[random_indices, ]

data_prcd <- as.matrix(random_sample)

head(data_prcd,1)
```
## Do not run 
```{r}

## Stack the data (with noise) to make the sample size larger.
## Probably not needed in this case 
data_stack <- data_prcd[rep(1:nrow(data_prcd), 2), ]
n_stack <- dim(data_stack)[1]
data_noise <- mvtnorm::rmvnorm(n_stack, sigma = diag(apply(data_stack,2,var))/4)
data_expd <- data_stack + data_noise
rm(data_stack, data_noise)
```

```{r}
colnames(all_merged_2000)
```

```{r}
data_prcd[,49]
```


```{r}
## Using the expanded data (data_expd) define the outcome, covariates, and exposure variables.
Y <- data_prcd[,49] # death rate (percentage)

X <- data_prcd[, c(46:48,50:55, 4:5, 8:13)]
# Convert character matrix to a numeric matrix element-wise
X_numeric <- matrix(as.numeric(X), nrow = nrow(X))
# Column names explanation:
# [4] "mean_bmi"
# [5] "smoke_rate"
# [8] "medhouseholdincome"
# [9] "medianhousevalue"
# [10] "poverty"
# [11] "education"
# [12] "popdensity"
# [13] "pct_owner_occ"
# [46] "female_percentage"
# [47] "dual_percentage"
# [48] "mean_age"
# [50] "percentage_race_labelAsian"
# [51] "percentage_race_labelBlack"
# [52] "percentage_race_labelOther"
# [53] "percentage_race_labelWhite"
# [54] "percentage_race_labelHispanic"
# [55] "percentage_race_labelNorth_American_Native"

W <- data_prcd[,c(14:34, 37:44)]
# [1] "summer_tmmx"         "winter_tmmx"         "summer_rmax"         "winter_rmax"        
# [5] "pm25"                "ozone"               "br"                  "ca"                 
# [9] "cu"                  "ec"                  "fe"                  "k"                  
#[13] "nh4"                 "ni"                  "no3"                 "oc"                 
#[17] "pb"                  "si"                  "so4"                 "v"                  
#[21] "z"                   "randall_martin_PM25" "randall_martin_BC"   "randall_martin_NH4" 
#[25] "randall_martin_NIT"  "randall_martin_OM"   "randall_martin_SO4"  "randall_martin_SOIL"
#[29] "randall_martin_SS"  



# Convert character matrix to a numeric matrix element-wise
W_numeric <- matrix(as.numeric(W), nrow = nrow(W))
```

```{r}
## Define two levels of exposures we would like to compare.
W0 <- apply(W_numeric, 2, quantile, 0.4, na.rm = TRUE)
W1 <- apply(W_numeric, 2, quantile, 0.6, na.rm = TRUE)
```


```{r}
Y_numeric <- as.numeric(Y)
X_numeric <- matrix(as.numeric(X), nrow = nrow(X))
W1_numeric <- as.numeric(W1)
W0_numeric <- as.numeric(W0)

```


```{r}

## Fit the model.
fit <- SepBART_blk(Y = Y_numeric, X = X_numeric, W = W_numeric,
        Xtest = NULL, W1 = W1_numeric, W0 = W0_numeric,
        nMCMC=1000,BurnIn_portion=0.2,stepsize=5)

```

```{r}
# Save the 'fit' object as an RDS file
saveRDS(fit, "../data/output/2000_fit_result_test.rds")
```




# Request big memory node 
# run the code with a few data to see what does the outcome looks like
# suggest it is necessary to split the code in chunks, heejun will need to assist 
